# Deploy project to EC2 upon push to main.
name: Project Deployment to EC2
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-2
  
jobs:
  deployment:
    name: Deploy code to EC2 instance
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - name: Get latest pushed code
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # Only checkout the following files and directories
            backend/
            frontend/
            mcp-server/
            app.py
            uv.lock
      - name: Configure AWS Credentials
        # See for more info: https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with: 
          aws-region: ${{ env.AWS_REGION }}
          # See for more info about access keys: # https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo # TODO: CHANGE THIS
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
        
        
